### ISSUE TITLE
Learn

### ISSUE THREAD

**Issue by davidyapdy** [easydaniel/sanic-example#1]
Hi Daniel,

I'm trying to learn sanic and I dont really understand aiopg. I'm sorry if it's too much to ask but can you briefly let me know how is asynpg and aiopg differ ? Thank you very much!

**Comment by easydaniel** [comment]
AFAIK, aiopg is just a simple wrapper of psycopg2, you can deem aiopg is psycopg2 but can be used with asyncio;  however,  asyncpg seems to implement data type translation and preprocess to have better performance in communicating with Postgresql.
You can find more on asyncpg at [official document of asyncpg](https://magic.io/blog/asyncpg-1m-rows-from-postgres-to-python/)

Hope this solves your problem.

**Comment by davidyapdy** [comment]
ありがとうsaitamasan！

**Comment by easydaniel** [comment]
どういたしまして

**Comment by davidyapdy** [comment]
あなたわ日本人ですか？
